config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls')),
    path('categories/', include('categories.urls')),
    path('shops/', include('shops.urls')),
    path('products/', include('products.urls')),
    path('shopping-list/', include('shopping_list.urls')),
    path('friends/', include('friends.urls')),

    path('__debug__/', include('debug_toolbar.urls')),
]

friends/urls.py
from django.urls import path

from . import views

app_name = 'friends'

urlpatterns = [
    path('invite/', views.InviteCreateView.as_view(), name='create_invite'),
    path('list/', views.FriendsListView.as_view(), name='friends_list'),
    path('delete/', views.FriendDeleteView.as_view(), name='delete_friend'),

    path('invite/list/', views.InviteListView.as_view(), name='invites_list'),
    path('invite/delete/', views.InviteDeleteView.as_view(), name='delete_invite'),
    path('invite/decision/<int:send_from>/<int:response>', views.InviteChangeStatus.as_view(), name='invite_response'),



]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('list/', views.ProductListView.as_view(), name='list'),
    path('create/', views.ProductCreateView.as_view(), name='create'),
    path('update/<slug:slug>', views.ProductUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>', views.ProductDeleteView.as_view(), name='delete'),
]

shops/urls.py
from django.urls import path

from . import views

app_name = 'shops'

urlpatterns = [
    path('list/', views.ShopListView.as_view(), name='list'),
    path('create/', views.ShopCreateView.as_view(), name='create'),
    path('update/<slug:slug>', views.ShopUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>', views.ShopDeleteView.as_view(), name='delete'),
    path('reorder/<slug:slug>/<int:category>', views.ShopCategoriesReorderedView.as_view(), name='reorder'),
    path('reorder/<slug:slug>', views.ShopCategoriesReorderedView.as_view(), name='reorder'),

]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.CreateUserView.as_view(), name='signup')
    
]

templates/partials/_menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}">Shopping list</a>
        <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:home' %}">Home</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'shopping_list:list' %}">Shopping lists</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"} href="{% url 'products:list' %}">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shops:list' %}">Shops</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'categories:list' %}">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'friends:friends_list' %}">Friends</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:signup' %}">Sign up</a>
                    </li>
                {% endif %}

                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                {#                <li class="nav-item">#}
                {#                    <a class="nav-link disabled">Disabled</a>#}
                {#                </li>#}
            </ul>
        </div>
    </div>
</nav>