config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls')),
    path('categories/', include('categories.urls')),
    path('shops/', include('shops.urls')),
    path('products/', include('products.urls')),
    path('shopping-list/', include('shopping_list.urls')),
    path('friends/', include('friends.urls')),

    path('__debug__/', include('debug_toolbar.urls')),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

shopping_list/urls.py
from django.urls import path

from . import views

app_name = 'shopping_list'

urlpatterns = [
    path('list/', views.ShoppingListListView.as_view(), name='list'),
    path('list/history/', views.ShoppingListHistoryListView.as_view(), name='history'),
    path('list/favourites/', views.ShoppingListFavouritesListView.as_view(), name='favourites'),
    path('create/', views.ShoppingListCreateView.as_view(), name='create'),
    path('update/<slug:slug>', views.ShoppingListUpdateView.as_view(), name='update'),
    path('update/<slug:slug>/<int:product_id>',
         views.ShoppingListUpdateProductStatus.as_view(),
         name='change_product_status'),
    path('update/finish/<slug:slug>', views.ShoppingListUpdateFinishStatus.as_view(), name='change_finish_status'),
    path('delete/<slug:slug>', views.ShoppingListDeleteView.as_view(), name='delete'),
    path('share/<slug>', views.ShoppingListShareView.as_view(), name='share'),
    path('view/comment/<slug:slug>/<int:product_id>',
         views.ShoppingListViewComment.as_view(),
         name='view_comment'),

]

shopping_list/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.text import slugify

from products.models import UNITS_OF_MEASUREMENT, Product
from shops.models import Shop


class ShoppingList(models.Model):
    """Representation of shopping list"""
    name = models.CharField(max_length=255)
    is_finished = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    is_favourite = models.BooleanField(default=False)
    show_bought = models.BooleanField(default=False)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE, blank=True, null=True)
    products = models.ManyToManyField(Product, through='ProductShoppingList')
    shared_with_list = models.ManyToManyField(get_user_model(), related_name='shared_with',  blank=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class ProductShoppingList(models.Model):
    """Representation of relation between shopping lists and products"""
    shopping_list = models.ForeignKey('ShoppingList', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    is_bought = models.BooleanField(default=False)
    amount = models.FloatField(validators=[MinValueValidator(0)],
                               blank=True,
                               null=True, )
    unit_of_measurement = models.CharField(max_length=20,
                                           choices=UNITS_OF_MEASUREMENT,
                                           blank=True,
                                           null=True, )
    comment = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'Shopping list: {self.shopping_list.name}, product: {self.product.name}'

shopping_list/forms.py
from django import forms
from django.forms import inlineformset_factory

from shopping_list.models import ShoppingList, ProductShoppingList
from shops.models import Shop


class CreateShoppingListForm(forms.ModelForm):
    class Meta:
        model = ShoppingList
        fields = ('name', 'is_favourite', 'shop')

    def __init__(self, *args, **kwargs):
        """Add request data to form and setup queryset to get only current user related objects"""
        self.request = kwargs.pop('request')
        super(CreateShoppingListForm, self).__init__(*args, **kwargs)
        self.fields['shop'].queryset = Shop.objects.filter(user=self.request.user)


class ShoppingListForm(forms.ModelForm):
    class Meta:
        model = ShoppingList
        fields = ('name',)

    def __init__(self, *args, **kwargs):
        """Add request data to form and setup queryset to get only current user related objects"""
        self.request = kwargs.pop('request')
        super(ShoppingListForm, self).__init__(*args, **kwargs)
        self.fields['shop'].queryset = Shop.objects.filter(user=self.request.user)


class ProductsMetaForm(forms.ModelForm):
    class Meta:
        model = ProductShoppingList
        fields = ('product', 'amount', 'unit_of_measurement', 'comment')


class ShowCommentForm(forms.ModelForm):

    class Meta:
        model = ProductShoppingList
        fields = ('comment',)

shopping_list/views.py
from django import views
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import CreateView, UpdateView, DeleteView

from friends.models import UserFriend
from products.models import UNITS_OF_MEASUREMENT
from shopping_list.forms import CreateShoppingListForm
from shopping_list.mixins import ShoppingListMixins
from shopping_list.models import ShoppingList


class ShoppingListCreateView(LoginRequiredMixin, CreateView, ShoppingListMixins):
    """Display view for create new category"""
    success_url = reverse_lazy('shopping_list:list')
    model = ShoppingList
    form_class = CreateShoppingListForm
    template_name = 'shopping_list/create.html'
    context_object_name = 'shopping_list'

    def get_initial(self):
        """Setup initial values for new shopping list in case building it from template shopping list"""

        user = self.request.user
        source_slug = self.request.GET.get('source')
        source_shopping_list = ShoppingList.objects.filter(user=user, slug=source_slug)
        initial = super().get_initial()

        if source_shopping_list.exists():
            initial['name'] = source_shopping_list.first().name
            initial['shop'] = source_shopping_list.first().shop

        return initial

    def get_context_data(self, **kwargs):
        """Load additional data to view about products and units of measurement"""
        context = super(ShoppingListCreateView, self).get_context_data(**kwargs)
        user = self.request.user
        source_slug = self.request.GET.get('source')
        source_shopping_list = ShoppingList.objects.filter(user=user, slug=source_slug)

        if source_shopping_list:
            source_shopping_list = source_shopping_list.first()
        else:
            source_shopping_list = None

        context['products_by_categories_and_favourites'] = self.get_all_products(user, source_shopping_list)
        context['UNITS_OF_MEASUREMENT'] = UNITS_OF_MEASUREMENT
        # context['source_shopping_list'] = source_shopping_list
        return context

    def form_valid(self, form):
        """Manually save data (shopping list and then products in shopping list) from form"""
        user = self.request.user
        form.instance.user = user
        try:
            products_to_save = self.get_products_for_shopping_list(user, self.request.POST)
            shopping_list = form.save()
            user_id = str(shopping_list.user_id)
            shopping_list_id = str(shopping_list.id)
            shopping_list.slug = slugify('-'.join((user_id, shopping_list_id)))
            shopping_list.save()
            self.save_products_in_shopping_list(products_to_save, shopping_list)
        except ValueError:
            return super().form_invalid(form)
        except ObjectDoesNotExist:
            return super().form_invalid(form)

        return redirect('shopping_list:list')

    def get_form_kwargs(self):
        """ Passes the request object to the form class.
         This is necessary to only display members that belong to a given user"""

        kwargs = super(ShoppingListCreateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class ShoppingListUpdateView(LoginRequiredMixin, UpdateView, ShoppingListMixins):
    """Display view for editing existing shopping list"""
    success_url = reverse_lazy('shopping_list:list')
    model = ShoppingList
    form_class = CreateShoppingListForm
    template_name = 'shopping_list/create.html'

    def get_context_data(self, **kwargs):
        """Add additional data about products for selected shopping list and constant for uom"""
        context = super(ShoppingListUpdateView, self).get_context_data(**kwargs)
        user = self.request.user

        shopping_list = context['shoppinglist']

        context['products_by_categories_and_favourites'] = self.get_all_products(user, shopping_list)
        context['UNITS_OF_MEASUREMENT'] = UNITS_OF_MEASUREMENT
        return context

    def get_form_kwargs(self):
        """ Passes the request object to the form class.
         This is necessary to only display members that belong to a given user"""

        kwargs = super(ShoppingListUpdateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        """Manually save data (shopping list and then products in shopping list) from form"""

        user = self.request.user
        form.instance.user = user
        try:
            products_to_save = self.get_products_for_shopping_list(user, self.request.POST)
            shopping_list = form.save()
            self.clear_products_in_shopping_list(shopping_list)
            self.save_products_in_shopping_list(products_to_save, shopping_list)
        except ValueError:
            return super().form_invalid(form)
        except ObjectDoesNotExist:
            return super().form_invalid(form)

        return redirect('shopping_list:list')


class ShoppingListDeleteView(LoginRequiredMixin, DeleteView):
    """Delete selected shopping list"""
    success_url = reverse_lazy('shopping_list:list')
    model = ShoppingList
    template_name = '../templates/delete_confirmation.html'
    extra_context = {'cancel_operation_url': 'shopping_list:list'}


class ShoppingListListView(LoginRequiredMixin, views.View, ShoppingListMixins):
    """Display all active shopping lists for logged user"""

    def get(self, request):
        """Get and display all active shopping lists that are owned or shared to the active user"""
        user = request.user

        shopping_lists = ShoppingList.objects.filter(Q(user=user) | Q(shared_with_list=user),
                                                     is_finished=False).order_by('-created_on')
        data_to_render = self.get_shopping_lists(shopping_lists, user)

        return render(request, 'shopping_list/main_list.html', {'data_to_render': data_to_render})


class ShoppingListUpdateProductStatus(LoginRequiredMixin, views.View):
    """Change selected product bought status on selected shopping list to opposite"""

    def post(self, request, slug, product_id):
        """Try to get requested product from selected shopping list and change it status to opposite if succeed"""
        user = request.user
        shopping_list = ShoppingList.objects.filter(user=user, slug=slug)

        if shopping_list:
            shopping_list = shopping_list.first()
            p = shopping_list.productshoppinglist_set.get(product_id=product_id)
            p.is_bought = not p.is_bought
            p.save()

        return redirect('shopping_list:list')


class ShoppingListViewComment(LoginRequiredMixin, views.View):
    """Display view with comment for selected product from selected shopping list"""

    def get(self, request, slug, product_id):
        """Try to get comment for selected product from selected shopping list and render view with it"""
        user = request.user
        previous = request.GET.get('previous')

        shopping_list = ShoppingList.objects.filter(user=user, slug=slug)
        if not shopping_list:
            return redirect('shopping_list:list')

        product = shopping_list.first().productshoppinglist_set.filter(product_id=product_id)
        if not product:
            return redirect('shopping_list:list')

        return render(request, 'shopping_list/view_comment.html', {'product': product.first(), 'previous': previous})

    def post(self, request, slug, product_id):
        """Redirect to shopping list view that called comment view"""
        previous = request.POST.get('previous')
        return redirect(previous)


class ShoppingListUpdateFinishStatus(LoginRequiredMixin, views.View):
    """Change selected shopping list finished status to opposite"""
    def post(self, request, slug):
        """Try to get selected shopping list for current user and change it finished status to opposite"""
        user = request.user
        shopping_list = ShoppingList.objects.filter(user=user, slug=slug)

        if shopping_list:
            shopping_list = shopping_list.first()
            shopping_list.is_finished = not shopping_list.is_finished
            shopping_list.save()

        return redirect('shopping_list:list')


class ShoppingListHistoryListView(LoginRequiredMixin, views.View, ShoppingListMixins):
    """Display all finished shopping lists for logged user"""

    def get(self, request):
        """Get and display all finished shopping lists that are owned by the active user"""
        user = request.user

        shopping_lists = ShoppingList.objects.filter(user=user, is_finished=True).order_by('-created_on')
        data_to_render = self.get_shopping_lists(shopping_lists)

        return render(request, 'shopping_list/history_list.html', {'data_to_render': data_to_render})


class ShoppingListFavouritesListView(LoginRequiredMixin, views.View, ShoppingListMixins):
    """Display all favourite shopping lists for logged user"""

    def get(self, request):
        """Get and display all favourite shopping lists that are owned by the active user"""
        user = request.user

        shopping_lists = ShoppingList.objects.filter(user=user, is_favourite=True).order_by('created_on')
        data_to_render = self.get_shopping_lists(shopping_lists)

        return render(request, 'shopping_list/favourites_list.html', {'data_to_render': data_to_render})


class ShoppingListShareView(LoginRequiredMixin, UpdateView):
    """Display view with friends list for selecting to whom shopping list should be shared with"""
    model = ShoppingList
    fields = ('name',)
    success_url = reverse_lazy('shopping_list:list')
    template_name = 'shopping_list/friend_list.html'

shopping_list/templates/shopping_list/create.html
{% extends 'base.html' %}

{% block title %}
    Create shopping_list
{% endblock %}

{% block container %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% for data in products_by_categories_and_favourites %}
            <ul class="list-group list-group-flush mt-3">
                {% for products_set in data.1 %}
                    {% if products_set.0 == '' %}
                        <li class="list-group-item list-group-item-info">No category assigned</li>
                    {% else %}
                        <li class="list-group-item list-group-item-info">{{ products_set.0 }}</li>
                    {% endif %}

                    <ul>
                        {% for product in products_set.1 %}
                            {% if data.0 %}
                                <li class="list-group-item d-flex align-items-start list-group-item-warning">
                                    {% else %}
                                <li class="list-group-item d-flex align-items-start">
                            {% endif %}

                        <div class="container col-2">
                            <input type="checkbox" name="product-id-{{ product.id }}"
                                   id="product-id-{{ product.id }}" {% if product.checked %} checked {%  endif %}>
                            <label for="product-id-{{ product.id }}">{{ product.name }}</label>
                        </div>

                        <div class="container">
                            <div class="row ">

                                <div class="row col-sm-3">
                                    <input type="number"
                                           name="amount-id-{{ product.id }}"
                                           id="amount-id-{{ product.id }}" min="0"
                                           value="{{ product.amount|floatformat:0 }}"
                                           class="col-6">
                                    <label class="col-6" for="amount-id-{{ product.id }}">:Amount</label>
                                </div>

                                <div class="col-sm-2">
                                    <select name="uom-id-{{ product.id }}" id="uom-id-{{ product.id }}">
                                        <option value="None" selected>--------</option>
                                        {% for uom in UNITS_OF_MEASUREMENT %}
                                            <option value={{ uom.0 }}
                                                            {% if product.uom == uom.0 %}
                                                                selected
                                                            {% endif %}>{{ uom.1 }}</option>
                                        {% endfor %}
                                    </select>
                                    <label for="uom-id-{{ product.id }}">:Units</label>
                                </div>

                                <div class="row col-sm-7">
                                                <textarea name="comment-id-{{ product.id }}"
                                                          id="comment-id-{{ product.id }}" cols="20"
                                                          rows="2" class="col-6">{{ product.comment }}</textarea>
                                    <label class="col-6" for="comment-id-{{ product.id }}">:Comment</label>
                                </div>
                            </div>
                        </div>
                        </li>
                        {% endfor %}
                    </ul>
                {% endfor %}
            </ul>
        {% endfor %}

        <input type="submit" value="Save" class="btn btn-sm btn-success mt-3">
        <a href="{% url 'shopping_list:list' %}" class="btn btn-sm btn-success mt-3">Cancel</a>
    </form>
{% endblock %}

shopping_list/templates/shopping_list/favourites_list.html
{% extends 'base.html' %}

{% block title %}
    Shopping lists
{% endblock %}

{% block container %}
    <h2>Shopping lists - favourites</h2>
    <div class=" list-group list-group-flush d-flex justify-content-start align-items-start">
        <div class="">
            <a href="{% url 'shopping_list:list' %}" class="btn btn-success btn-lg">Back</a>
        </div>
    </div>
    <ul class="list-group list-group-flush mt-3">
        {% for item in data_to_render %}
            <li class="list-group-item list-group-item-info d-flex mt-3 justify-content-between align-items-start">
                <div class="row col-6">
                    <div class="col-6">
                        <span>{{ item.0.name }}</span>
                    </div>
                    <div class="col-6">
                        {% if item.0.shop != None %}
                            Shop: <span>{{ item.0.shop }}</span>
                        {% else %}
                            No shop chosen
                        {% endif %}
                    </div>
                </div>
                <div class="">
                    <a href="{% url 'shopping_list:create' %}?source={{ item.0.slug }}" class="btn btn-success btn-sm me-2">Use as template</a>
                    <a href="{% url 'shopping_list:delete' slug=item.0.slug %}" class="btn btn-danger btn-sm">Delete</a>
                </div>
            </li>
            <ul class="">
                {% for product in item.1 %}
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="row col-6" id="{{ item.0.id }}_{{ product.product_id }}">
                            <div class="col-6">
                                <span> {{ product.product }}</span>
                            </div>
                            <div class="col">
                                <span>{{ product.amount|floatformat:0 }}</span>
                                {% if product.amount != '' and product.unit_of_measurement != 'None' %}
                                    <span>{{ product.unit_of_measurement }}</span>
                                {% endif %}
                            </div>
                        </div>
                        <div>
                            {% if product.comment != '' %}
                                <a href="{% url 'shopping_list:view_comment' slug=item.0.slug product_id=product.product_id %}?previous={{ request.path|urlencode }}#{{ item.0.id }}_{{ product.product_id }}"
                                   class="btn btn-success btn-sm">View comment</a>
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>
{% endblock %}

shopping_list/templates/shopping_list/friend_list.html
{% extends 'base.html' %}

{% block title %}
    Sharing
{% endblock %}

{% block container %}
    <h4>Sharing shopping list - {{ shopping_list.name }}</h4>
    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="list-id" value="{{ shopping_list.id }}">
        {% for item in data_to_display %}
            <ul class="list-group list-group-flush mt-3">
                <li class="list-group-item d-flex align-items-start">
                    <div class="container">
                        <input type="checkbox" name="friend-id-{{ item.friend.friend.id }}"
                               id="friend-id-{{ item.friend.id }}" {% if item.already_shared %} checked {% endif %}>
                        <label for="friend-id-{{ item.friend.id }}">{{ item.friend.friend }}</label>
                    </div>
                </li>
            </ul>
        {% endfor %}

        <input type="submit" value="Share" class="btn btn-success mt-3">
        <a href="{% url 'shopping_list:list' %}" class="btn btn-danger mt-3">Cancel</a>
    </form>

{% endblock %}

shopping_list/templates/shopping_list/history_list.html
{% extends 'base.html' %}

{% block title %}
    Shopping lists
{% endblock %}

{% block container %}
    <h2>Shopping lists - history</h2>
    <div class=" list-group list-group-flush d-flex justify-content-start align-items-start mb-3">
        <div class="">
            <a href="{% url 'shopping_list:list' %}" class="btn btn-success btn-lg">Back</a>
        </div>
    </div>
    <ul class="list-group list-group-flush">
        {% for item in data_to_render %}
            <li class="list-group-item list-group-item-info d-flex mt-3 justify-content-between align-items-start">
                <div class="row col-6">
                    <div class="col-6">
                        <span>{{ item.0.name }}</span>
                    </div>
                    <div class="col-6">
                        {% if item.0.shop != None %}
                            Shop: <span>{{ item.0.shop }}</span>
                        {% else %}
                            No shop chosen
                        {% endif %}
                    </div>
                </div>
                <div class="">
                    <a href="{% url 'shopping_list:create' %}?source={{ item.0.slug }}"
                       class="btn btn-success btn-sm me-2">Use as template</a>
                    <div class="d-inline-flex me-2" style="width: 6rem">
                        <form action="{% url 'shopping_list:change_finish_status' slug=item.0.slug %}" method="post">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-warning btn-sm" value="Not finished">
                        </form>
                    </div>
                    {#                    <a href="{% url 'shopping_list:change_finish_status' slug=item.0.slug %}"#}
                    {#                       class="btn btn-warning btn-sm me-2">Not finished</a>#}
                    <a href="{% url 'shopping_list:delete' slug=item.0.slug %}"
                       class="btn btn-danger btn-sm">Delete</a>
                </div>
            </li>
            <ul class="">
                {% for product in item.1 %}
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="row col-6" id="{{ item.0.id }}_{{ product.product_id }}">
                            <div class="col-6">
                                <span> {{ product.product }}</span>
                            </div>
                            <div class="col">
                                <span>{{ product.amount|floatformat:0 }}</span>
                                {% if product.amount != '' and product.unit_of_measurement != 'None' %}
                                    <span>{{ product.unit_of_measurement }}</span>
                                {% endif %}
                            </div>
                        </div>
                        <div>
                            {% if product.comment != '' %}
                                <a href="{% url 'shopping_list:view_comment' slug=item.0.slug product_id=product.product_id %}?previous={{ request.path|urlencode }}#{{ item.0.id }}_{{ product.product_id }}"
                                   class="btn btn-success btn-sm">View comment</a>
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>
{% endblock %}

shopping_list/templates/shopping_list/main_list.html
{% extends 'base.html' %}

{% block title %}
    Shopping lists
{% endblock %}

{% block container %}
    <h2>Shopping lists</h2>
    <div class=" list-group list-group-flush d-flex justify-content-start align-items-start">
        <div class="">
            <a href="{% url 'shopping_list:create' %}" class="btn btn-success btn-lg">New shopping list</a>
            <a href="{% url 'shopping_list:favourites' %}" class="btn btn-success btn-lg">Favourites</a>
            <a href="{% url 'shopping_list:history' %}" class="btn btn-success btn-lg">History</a>
        </div>
    </div>
    <ul class="list-group list-group-flush mt-3">
        {% for item in data_to_render %}

            <li class="list-group-item list-group-item-info d-flex mt-3 justify-content-between align-items-start">
                <div class="row col-6">
                    <div class="col-6">
                        <span>{{ item.0.name }}</span>
                    </div>
                    <div class="col-6">
                        {% if item.0.shop != None %}
                            Shop: <span>{{ item.0.shop }}</span>
                        {% else %}
                            No shop chosen
                        {% endif %}
                    </div>
                </div>
                <div>

                    {% if item.2 %}
                        <button disabled class="btn btn-info btn-sm me-2">Shared</button>
                    {% else %}
                        <a href="{% url 'shopping_list:share' slug=item.0.slug %}" class="btn btn-info btn-sm me-2">Share</a>
                        <a href="{% url 'shopping_list:update' slug=item.0.slug %}"
                           class="btn btn-warning btn-sm me-2">Edit</a>
                        <a href="{% url 'shopping_list:delete' slug=item.0.slug %}"
                           class="btn btn-danger btn-sm me-2">Delete</a>
                    {% endif %}
                    <div class="d-inline-flex" style="width: 4rem">
                        <form action="{% url 'shopping_list:change_finish_status' slug=item.0.slug %}" method="post">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-success btn-sm" value="Finished">
                        </form>
                    </div>
                </div>
            </li>
            <ul class="">
                {% for product in item.1 %}
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="row col-6" id="{{ item.0.id }}_{{ product.product_id }}">

                            <div class="col-6">
                                {% if product.is_bought %}
                                    <del>
                                {% endif %}
                                <span> {{ product.product }}</span>
                                {% if product.is_bought %}
                                    </del>
                                {% endif %}
                            </div>
                            <div class="col">
                                {% if product.is_bought %}
                                    <del>
                                {% endif %}
                                <span>{{ product.amount|floatformat:0 }}</span>
                                {% if product.amount != '' and product.unit_of_measurement != 'None' %}
                                    <span>{{ product.unit_of_measurement }}</span>
                                {% endif %}
                                {% if product.is_bought %}
                                    </del>
                                {% endif %}
                            </div>
                        </div>
                        <div>
                            {% if product.comment != '' %}
                                <a href="{% url 'shopping_list:view_comment' slug=item.0.slug product_id=product.product_id %}?previous={{ request.path|urlencode }}#{{ item.0.id }}_{{ product.product_id }}"
                                   class="btn btn-success btn-sm me-2">View comment</a>
                            {% endif %}
                            <div class="d-inline-flex" style="width: 4rem">
                                <form action="{% url 'shopping_list:change_product_status' slug=item.0.slug product_id=product.product_id %}#{{ item.0.id }}_{{ product.product_id }}"
                                      method="post">
                                    {% csrf_token %}
                                    {% if product.is_bought %}
                                        <input type="submit" class="btn btn-success btn-sm" value="Uncheck">
                                    {% else %}
                                        <input type="submit" class="btn btn-danger btn-sm" value="Check">
                                    {% endif %}
                                </form>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>
{% endblock %}