categories/urls.py
from django.urls import path

from . import views

app_name = 'categories'

urlpatterns = [
    path('list/', views.CategoryListView.as_view(), name='list'),
    path('create/', views.CategoryCreateView.as_view(), name='create'),
    path('update/<slug:slug>', views.CategoryUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>', views.CategoryDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls')),
    path('categories/', include('categories.urls')),
    path('shops/', include('shops.urls')),
    path('products/', include('products.urls')),
    path('shopping-list/', include('shopping_list.urls')),
    path('friends/', include('friends.urls')),

    path('__debug__/', include('debug_toolbar.urls')),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

categories/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.text import slugify


class Category(models.Model):
    """Model of products category"""
    name = models.CharField(max_length=255)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    is_favourite = models.BooleanField(default=False)
    slug = models.SlugField(unique=1)

    class Meta:
        unique_together = ('name', 'user')

    def save(self, *args, **kwargs):
        """Build custom slug on object save"""
        pk = str(self.user_id)
        name = self.name
        self.slug = slugify('-'.join((pk, name)))
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

categories/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DeleteView

from categories.models import Category


class CategoryCreateView(LoginRequiredMixin, CreateView):
    """Display view for create new category"""

    success_url = reverse_lazy('categories:list')
    model = Category
    fields = ('name', 'is_favourite')
    template_name = 'categories/create.html'

    def form_valid(self, form):
        """Add user information, necessary to save category object"""
        form.instance.user = self.request.user
        return super().form_valid(form)


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    """Display view for editing existing category"""
    success_url = reverse_lazy('categories:list')
    model = Category
    fields = ('name', 'is_favourite')
    template_name = 'categories/create.html'


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    """Delete selected category"""
    success_url = reverse_lazy('categories:list')
    model = Category
    template_name = '../templates/delete_confirmation.html'
    extra_context = {'cancel_operation_url': 'categories:list'}


class CategoryListView(LoginRequiredMixin, ListView):
    """Display all categories for logged user"""
    template_name = 'categories/list.html'
    model = Category
    context_object_name = 'categories'
    allow_empty = 1

    def get_queryset(self):
        """Setup queryset to show only categories for current user sorted by favourites and name"""
        return Category.objects.filter(user=self.request.user).order_by('-is_favourite', 'name')

categories/templates/categories/create.html
{% extends 'base.html' %}

{% block title %}
    Create category
{% endblock %}

{% block container %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" class="btn btn-sm btn-success">
        <a href="{% url 'categories:list' %}" class="btn btn-sm btn-success">Cancel</a>
    </form>
{% endblock %}

categories/templates/categories/list.html
{% extends 'list_template.html' %}

{% block title %}
    Categories list
{% endblock %}

{% block header %}
    <h2>Categories</h2>
{% endblock %}

{% block create_url %}
    {% url 'categories:create' %}
{% endblock %}

{% block create_description %}
    New category
{% endblock %}

{% block favourite_list %}
    {% for category in categories %}
        {% if category.is_favourite %}
            <li class="list-group-item d-flex justify-content-between align-items-start list-group-item-warning">
                <span class="text-black ">{{ category.name }}</span>
                <div>
                    <a href="{% url 'categories:update' slug=category.slug %}" class="btn btn-success btn-sm">Edit</a>
                    <a href="{% url 'categories:delete' slug=category.slug %}" class="btn btn-danger btn-sm">Delete</a>
                </div>
            </li>
        {% endif %}
    {% endfor %}
{% endblock %}

{% block not_favourite_list %}
    {% for category in categories %}
        {% if not category.is_favourite %}
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <span class="text-black ">{{ category.name }}</span>
                <div>
                    <a href="{% url 'categories:update' slug=category.slug %}" class="btn btn-success btn-sm">Edit</a>
                    <a href="{% url 'categories:delete' slug=category.slug %}" class="btn btn-danger btn-sm">Delete</a>
                </div>
            </li>
        {% endif %}
    {% endfor %}
{% endblock %}