config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls')),
    path('categories/', include('categories.urls')),
    path('shops/', include('shops.urls')),
    path('products/', include('products.urls')),
    path('shopping-list/', include('shopping_list.urls')),
    path('friends/', include('friends.urls')),

    path('__debug__/', include('debug_toolbar.urls')),
]

friends/urls.py
from django.urls import path

from . import views

app_name = 'friends'

urlpatterns = [
    path('invite/', views.InviteCreateView.as_view(), name='create_invite'),
    path('list/', views.FriendsListView.as_view(), name='friends_list'),
    path('delete/', views.FriendDeleteView.as_view(), name='delete_friend'),

    path('invite/list/', views.InviteListView.as_view(), name='invites_list'),
    path('invite/delete/', views.InviteDeleteView.as_view(), name='delete_invite'),
    path('invite/decision/<int:send_from>/<int:response>', views.InviteChangeStatus.as_view(), name='invite_response'),



]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

friends/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models


class UserFriend(models.Model):
    """Representation of user friends"""
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='user')
    friend = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='friend')
    created = models.DateTimeField(auto_now_add=True)
    share_all_lists = models.BooleanField(default=0)

    class Meta:
        unique_together = ('user', 'friend')

    def __str__(self):
        return f'User: {self.user.name}, friend: {self.friend.name}'


class Invite(models.Model):
    """Representation of invites to friends list"""
    send_from = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='send_from')
    send_to = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='send_to', null=True)
    requested_friend_username = models.CharField(max_length=255)
    send_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('send_from', 'requested_friend_username')

    def __str__(self):
        return f'Send by: {self.send_from.name}, ' \
               f'requested username: {self.requested_friend_username}, ' \
               f'found user: {self.send_to.name}'

friends/forms.py
from django import forms
from django.core.exceptions import ValidationError

from friends.models import Invite, UserFriend


class InviteCreateForm(forms.ModelForm):
    class Meta:
        model = Invite
        fields = ('requested_friend_username',)
        labels = {
            'requested_friend_username': 'Enter friend username'
        }

    def __init__(self, *args, **kwargs):
        """Add request data to form"""
        self.request = kwargs.pop('request')
        super(InviteCreateForm, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        """Check if user don't invite him/herself or don't invite already invited user"""
        requested_username = self.cleaned_data.get('requested_friend_username')
        user = self.request.user
        if requested_username == user.username:
            raise ValidationError('You cannot invite yourself')
        friends = UserFriend.objects.filter(user=user, friend__username=requested_username)
        if friends:
            raise ValidationError('You are already friends')
        invite = Invite.objects.filter(send_from=user, requested_friend_username=requested_username)
        if invite:
            raise ValidationError('You already invited that person')

        return super().clean()


class InviteListForm(forms.ModelForm):
    class Meta:
        model = Invite
        fields = ('requested_friend_username',)
        labels = {
            'requested_friend_username': 'Username'
        }

friends/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseNotFound
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from django import views

from friends.forms import InviteCreateForm
from friends.models import UserFriend, Invite


class InviteCreateView(LoginRequiredMixin, CreateView):
    """Display view for create new invite"""
    model = Invite
    form_class = InviteCreateForm
    success_url = reverse_lazy('friends:friends_list')
    template_name = 'friends/create_invite.html'

    def form_valid(self, form):
        """Check if user with requested username exist and save it"""
        user = self.request.user
        form.instance.send_from = user
        send_to_username = form.cleaned_data['requested_friend_username']

        get_user_from_invitation = get_user_model().objects.filter(username=send_to_username)
        if get_user_from_invitation:
            form.instance.send_to = get_user_from_invitation.first()

        return super(InviteCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        """ Passes the request object to the form class.
         This is necessary to only display members that belong to a given user"""

        kwargs = super(InviteCreateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class InviteListView(LoginRequiredMixin, ListView):
    """Display view with send and received invites"""
    model = Invite
    template_name = 'friends/invites_list.html'
    context_object_name = 'invites'
    allow_empty = 1

    def get_queryset(self):
        """Setup queryset for only send and received invites of current user"""
        queryset = super().get_queryset()
        user = self.request.user
        queryset = queryset.filter(Q(send_from=user) | Q(send_to=user))
        return queryset


class InviteChangeStatus(LoginRequiredMixin, views.View):
    """Handle user accept or decline invite action"""

    def post(self, request, send_from, response):
        """Check if invite exist, resolve user decision and remove invite"""
        user = request.user
        invite = get_object_or_404(Invite, send_to_id=user.id, send_from_id=send_from)
        if response == 1:
            friend = get_user_model().objects.get(id=send_from)
            UserFriend.objects.create(user=user, friend=friend)
            UserFriend.objects.create(user=friend, friend=user)
            revert_invite = Invite.objects.filter(send_to_id=send_from, send_from_id=user.id)
            if revert_invite.exists():
                revert_invite.delete()

        if response in [0, 1]:
            invite.delete()

        return redirect('friends:invites_list')


#
class InviteDeleteView(LoginRequiredMixin, views.View):
    """Handle delete invite request"""

    def post(self, request):
        """Check if invite from current user for selected pk exist and remove it if so"""
        user = request.user
        pk = request.POST.get('pk')
        invite = get_object_or_404(Invite, send_from=user, id=pk)
        invite.delete()
        return redirect(reverse_lazy('friends:invites_list'))


class FriendsListView(LoginRequiredMixin, ListView):
    """Show view with friends list for current user"""
    model = UserFriend
    template_name = 'friends/friends_list.html'
    context_object_name = 'friends'

    def get_queryset(self):
        """Setup queryset to pick friends only for current user"""
        query_set = super(FriendsListView, self).get_queryset()
        query_set = query_set.filter(user=self.request.user)
        return query_set


class FriendDeleteView(LoginRequiredMixin, views.View):
    """Handle delete friend request"""

    def post(self, request):
        """Check if there is relation between current user and selected friend and delete it if so"""
        user_id = request.user.id
        friend_id = request.POST.get('pk')

        friend = UserFriend.objects.filter(user_id=user_id, friend_id=friend_id)
        friend_reverse = UserFriend.objects.filter(user_id=friend_id, friend_id=user_id)
        if not friend and not friend_reverse:
            return HttpResponseNotFound('No object found')
        if friend:
            friend.first().delete()
        if friend_reverse:
            friend_reverse.first().delete()

        return redirect(reverse_lazy('friends:friends_list'))

friends/templates/friends/create_invite.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block container %}
    <a href="{% url 'friends:friends_list' %}" class="btn btn-success btn-lg mb-3">Back</a>
    <form action=""method="post">
    {% csrf_token %}
    <p class="mt-3">{{ form }}</p>
        <input type="submit" name="save" id="save" class="btn btn-success mt-3">
    </form>
{% endblock %}

friends/templates/friends/friends_list.html
{% extends 'base.html' %}

{% block title %}
    Friends
{% endblock %}

{% block container %}
    <a href="{% url 'friends:create_invite' %}" class="btn btn-success btn-lg">Invite</a>
    <a href="{% url 'friends:invites_list' %}" class="btn btn-success btn-lg">Invites</a>
    <table class="table">
        <thead>
        <tr>
            <th scope="col" style="width: 90%">Friends</th>
            <th scope="col" style="width: 10%"></th>
        </tr>
        </thead>
        <tbody>
        {% for friend in friends %}

            <tr>
                <td>
                    {{ friend.friend }}
                </td>
                <td>
                    <form action="{% url 'friends:delete_friend' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="pk" value="{{ friend.friend_id }}">
                        <input type="submit" value="Remove" class="btn btn-danger btn-sm">
                    </form>
                </td>
            </tr>

        {% endfor %}
        </tbody>
    </table>
{% endblock %}

friends/templates/friends/invites_list.html
{% extends 'base.html' %}

{% block title %}
    Invites
{% endblock %}

{% block container %}

    <a href="{% url 'friends:friends_list' %}" class="btn btn-success btn-lg mb-3">Back</a>
    <div class="row">
        <div class="col-sm-6">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col" style="width: 80%">Invited by</th>
                    <th scope="col" style="width: 10%"></th>
                    <th scope="col" style="width: 10%"></th>
                </tr>
                </thead>
                <tbody>
                {% for invite in invites %}
                    {% if invite.send_to == request.user %}
                        <tr>
                            <td>
                                {{ invite.send_from.username }}
                            </td>
                            <td>
                                <div class="d-inline-flex" style="width: 4rem">
                                    <form action="{% url 'friends:invite_response' send_from=invite.send_from_id response=1 %}"
                                          method="post">
                                        {% csrf_token %}
                                        <input type="submit" class="btn btn-success btn-sm" value="Accept">
                                    </form>
                                </div>
                            </td>
                            <td>
                                <div class="d-inline-flex" style="width: 4rem">
                                    <form action="{% url 'friends:invite_response' send_from=invite.send_from_id response=0 %}"
                                          method="post">
                                        {% csrf_token %}
                                        <input type="submit" class="btn btn-danger btn-sm" value="Decline">
                                    </form>
                                </div>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-sm-6">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col" style="width: 80%">Send to</th>
                    <th scope="col" style="width: 10%"></th>
                    <th scope="col" style="width: 10%"></th>
                </tr>
                </thead>
                <tbody>
                {% for invite in invites %}
                    {% if invite.send_from == request.user %}
                        <tr>
                            <td>
                                {{ invite.requested_friend_username }}
                            </td>
                            <td>
                                <form action="{% url 'friends:delete_invite' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="pk" value="{{ invite.id }}">
                                    <input type="submit" value="Cancel" class="btn btn-danger btn-sm">
                                </form>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}